[workspace]
resolver = "2"

members = [
    "nethercade_bundler",
    "nethercade_console",
    "nethercade_core",
]

[workspace.dependencies]
hashbrown = "0.15"
serde = "1.0"
image = "0.25"
wasmtime = "28"
bytemuck = "1.21"