[package]
name = "nethercade_console"
version = "0.1.0"
edition = "2021"

[dependencies]
nethercade_core = { path = "../nethercade_core" }

eframe = { version = "0.30", features = ["wgpu"] }
wgpu = "23.0"
rodio = "0.20"
ggrs = "0.11"